---
- name: Converge
  hosts: all
  vars:
    chezmoi_repo: AnhQuanTrl
  pre_tasks:
    - name: Run pacman update before installation.
      pacman:
        update_cache: yes
        upgrade: yes
      become: true
      when: ansible_os_family == 'Archlinux'
  roles:
    - role: anhquantrl.dotfiles.chezmoi
