---
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-centos7-ansible:latest}
    pre_build_image: true
    privileged: true
    command: ""
    # platform: linux/amd64
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    ulimits:
      - nofile:65535:65535

provisioner:
  name: ansible
  inventory:
    host_vars:
      # setting for the platform instance named 'cdp-arch-ansible'
      # see "Problems with ulimits and makepkg" section below
      instance:
        ansible_user: ansible
